{
  "_meta": {
    "version": 3,
    "description": "Carrier Audit Templates with multilingual hints, auto-sheet detection & real ACC mappings",
    "fields": {
      "carrierMapping": "Primary column name expected in carrier invoice file",
      "boxmeMapping": "Primary column name expected in Boxme export file",
      "carrierHints": "Multilingual hints per field for auto-detection (EN/TH/VI)",
      "boxmeHints": "Multilingual hints per field for auto-detection"
    }
  },
  "GHN": {
    "name": "GHN (Giao Hàng Nhanh)",
    "carrierMapping": {
      "tracking": "Mã vận đơn",
      "bm_number": "Mã đơn hàng",
      "shipping_fee": "Phí vận chuyển",
      "cod_fee": "Tiền thu hộ",
      "weight": "Trọng lượng (kg)",
      "overweight_fee": "Phí vượt cân",
      "remote_fee": "Phụ phí vùng xa",
      "insurance_fee": "Phí bảo hiểm",
      "return_fee": "Phí hoàn hàng",
      "other_fees": "Phí khác",
      "status": "Trạng thái"
    },
    "carrierHints": {
      "tracking": ["Mã vận đơn", "Tracking Number", "Order Code", "เลขพัสดุ", "Ma van don"],
      "bm_number": ["Mã đơn hàng", "Order ID", "Customer Code", "รหัสพัสดุ"],
      "shipping_fee": ["Phí vận chuyển", "Cước phí", "Shipping Fee", "ค่าขนส่ง", "ค่าจัดส่ง"],
      "cod_fee": ["Tiền thu hộ", "COD", "COD Amount", "ค่า COD", "เงินเก็บเงินปลายทาง"],
      "weight": ["Trọng lượng", "Weight", "Khối lượng", "น้ำหนัก", "kg"],
      "overweight_fee": ["Phí vượt cân", "Overweight Fee", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Phụ phí vùng xa", "Remote Area", "Remote Fee", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Phí bảo hiểm", "Insurance Fee", "ค่าประกัน"],
      "return_fee": ["Phí hoàn hàng", "Return Fee", "ค่าคืน", "ค่าส่งคืน"],
      "other_fees": ["Phí khác", "Other Fees", "ค่าอื่นๆ"],
      "status": ["Trạng thái", "Status", "สถานะ"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "GHTK": {
    "name": "GHTK (Giao Hàng Tiết Kiệm)",
    "carrierMapping": {
      "tracking": "Mã vận đơn",
      "bm_number": "Mã đơn hàng",
      "shipping_fee": "Cước phí",
      "cod_fee": "Tiền thu hộ (COD)",
      "weight": "Khối lượng (kg)",
      "overweight_fee": "Phụ phí cân nặng",
      "remote_fee": "Phụ phí vùng xa",
      "insurance_fee": "Phí bảo hiểm",
      "return_fee": "Phí hoàn",
      "other_fees": "Phí khác",
      "status": "Trạng thái đơn"
    },
    "carrierHints": {
      "tracking": ["Mã vận đơn", "Tracking Number", "Ma van don", "เลขพัสดุ"],
      "bm_number": ["Mã đơn hàng", "Order Code", "Ma don hang"],
      "shipping_fee": ["Cước phí", "Phí vận chuyển", "Shipping Fee", "ค่าขนส่ง"],
      "cod_fee": ["Tiền thu hộ", "COD", "COD Amount", "ค่า COD"],
      "weight": ["Khối lượng", "Trọng lượng", "Weight", "น้ำหนัก"],
      "overweight_fee": ["Phụ phí cân nặng", "Phí vượt cân", "Overweight", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Phụ phí vùng xa", "Remote Area", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Phí bảo hiểm", "Insurance", "ค่าประกัน"],
      "return_fee": ["Phí hoàn", "Return Fee", "ค่าคืน"],
      "other_fees": ["Phí khác", "Other Fees", "ค่าอื่นๆ"],
      "status": ["Trạng thái đơn", "Trạng thái", "Status", "สถานะ"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "VTP": {
    "name": "Viettel Post",
    "carrierMapping": {
      "tracking": "Mã bưu gửi",
      "bm_number": "Mã khách hàng",
      "shipping_fee": "Cước chính",
      "cod_fee": "Tiền COD",
      "weight": "Trọng lượng",
      "overweight_fee": "Cước vượt cân",
      "remote_fee": "Phụ phí vùng xa",
      "insurance_fee": "Phí khai giá",
      "return_fee": "Phí hoàn",
      "other_fees": "Phụ phí khác",
      "status": "Trạng thái"
    },
    "carrierHints": {
      "tracking": ["Mã bưu gửi", "Ma buu gui", "Tracking Number", "เลขพัสดุ"],
      "bm_number": ["Mã khách hàng", "Customer Code", "Ma khach hang"],
      "shipping_fee": ["Cước chính", "Cuoc chinh", "Shipping Fee", "ค่าขนส่ง"],
      "cod_fee": ["Tiền COD", "COD", "COD Amount", "ค่า COD"],
      "weight": ["Trọng lượng", "Weight", "Trong luong", "น้ำหนัก"],
      "overweight_fee": ["Cước vượt cân", "Overweight", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Phụ phí vùng xa", "Remote Area", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Phí khai giá", "Insurance", "Bảo hiểm", "ค่าประกัน"],
      "return_fee": ["Phí hoàn", "Return Fee", "ค่าคืน"],
      "other_fees": ["Phụ phí khác", "Phí khác", "Other", "ค่าอื่นๆ"],
      "status": ["Trạng thái", "Status", "สถานะ"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "JT_VN": {
    "name": "J&T Express VN",
    "carrierMapping": {
      "tracking": "Mã vận đơn",
      "bm_number": "Mã đơn hàng KH",
      "shipping_fee": "Phí vận chuyển",
      "cod_fee": "Tiền thu hộ",
      "weight": "Trọng lượng tính cước (kg)",
      "overweight_fee": "Phí quá cân",
      "remote_fee": "Phụ phí vùng sâu vùng xa",
      "insurance_fee": "Phí bảo hiểm",
      "return_fee": "Phí chuyển hoàn",
      "other_fees": "Phí phát sinh",
      "status": "Trạng thái giao hàng"
    },
    "carrierHints": {
      "tracking": ["Mã vận đơn", "Tracking No", "Tracking Number", "เลขพัสดุ"],
      "bm_number": ["Mã đơn hàng KH", "Customer Order No", "รหัสพัสดุ"],
      "shipping_fee": ["Phí vận chuyển", "Delivery Fee", "Shipping Fee", "ค่าขนส่ง"],
      "cod_fee": ["Tiền thu hộ", "COD Amount", "COD", "ค่า COD"],
      "weight": ["Trọng lượng tính cước", "Chargeable Weight", "Weight", "น้ำหนัก"],
      "overweight_fee": ["Phí quá cân", "Overweight Fee", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Phụ phí vùng sâu vùng xa", "Phụ phí vùng xa", "Remote Area", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Phí bảo hiểm", "Insurance Fee", "ค่าประกัน"],
      "return_fee": ["Phí chuyển hoàn", "Phí hoàn", "Return Fee", "ค่าคืน"],
      "other_fees": ["Phí phát sinh", "Phí khác", "Other Fees", "ค่าอื่นๆ"],
      "status": ["Trạng thái giao hàng", "Trạng thái", "Status", "สถานะ"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "NINJA_VN": {
    "name": "Ninja Van VN",
    "carrierMapping": {
      "tracking": "Tracking ID",
      "bm_number": "Shipper Order ID",
      "shipping_fee": "Delivery Fee",
      "cod_fee": "COD Amount",
      "weight": "Weight (kg)",
      "overweight_fee": "Overweight Fee",
      "remote_fee": "Remote Area Surcharge",
      "insurance_fee": "Insurance Fee",
      "return_fee": "Return Fee",
      "other_fees": "Other Fees",
      "status": "Granular Status"
    },
    "carrierHints": {
      "tracking": ["Tracking ID", "Mã vận đơn", "Tracking Number", "เลขพัสดุ"],
      "bm_number": ["Shipper Order ID", "Mã đơn hàng", "รหัสพัสดุ"],
      "shipping_fee": ["Delivery Fee", "Phí vận chuyển", "Shipping Fee", "ค่าจัดส่ง"],
      "cod_fee": ["COD Amount", "Tiền thu hộ", "COD Fee", "ค่า COD"],
      "weight": ["Weight", "Trọng lượng", "Khối lượng", "น้ำหนัก"],
      "overweight_fee": ["Overweight Fee", "Phí vượt cân", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Remote Area Surcharge", "Phụ phí vùng xa", "Remote Area", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Insurance Fee", "Phí bảo hiểm", "ค่าประกัน"],
      "return_fee": ["Return Fee", "Phí hoàn", "ค่าคืน"],
      "other_fees": ["Other Fees", "Phí khác", "ค่าอื่นๆ"],
      "status": ["Granular Status", "Status", "Trạng thái", "สถานะ"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "BEST": {
    "name": "Best Express",
    "carrierMapping": {
      "tracking": "Mã vận đơn",
      "bm_number": "Mã tham chiếu",
      "shipping_fee": "Phí giao hàng",
      "cod_fee": "Tiền thu hộ",
      "weight": "Trọng lượng tính phí (kg)",
      "overweight_fee": "Phụ phí vượt cân",
      "remote_fee": "Phụ phí vùng xa",
      "insurance_fee": "Phí bảo hiểm hàng hóa",
      "return_fee": "Phí hoàn hàng",
      "other_fees": "Phí khác",
      "status": "Trạng thái"
    },
    "carrierHints": {
      "tracking": ["Mã vận đơn", "Tracking Number", "เลขพัสดุ"],
      "bm_number": ["Mã tham chiếu", "Reference Code", "รหัสอ้างอิง"],
      "shipping_fee": ["Phí giao hàng", "Shipping Fee", "Delivery Fee", "ค่าจัดส่ง"],
      "cod_fee": ["Tiền thu hộ", "COD Amount", "COD", "ค่า COD"],
      "weight": ["Trọng lượng tính phí", "Chargeable Weight", "Weight", "น้ำหนัก"],
      "overweight_fee": ["Phụ phí vượt cân", "Overweight Fee", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Phụ phí vùng xa", "Remote Area", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Phí bảo hiểm hàng hóa", "Insurance Fee", "ค่าประกัน"],
      "return_fee": ["Phí hoàn hàng", "Return Fee", "ค่าคืน"],
      "other_fees": ["Phí khác", "Other Fees", "ค่าอื่นๆ"],
      "status": ["Trạng thái", "Status", "สถานะ"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "SPX_VN": {
    "name": "Shopee Express VN",
    "carrierMapping": {
      "tracking": "Tracking number",
      "bm_number": "Customer TN",
      "shipping_fee": "Shipping fee",
      "cod_fee": "COD fee",
      "weight": "Chargeable weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote Area",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Administrative Fee",
      "status": "Remark"
    },
    "carrierHints": {
      "tracking": ["Tracking number", "Tracking Number", "Mã vận đơn", "เลขพัสดุ", "รหัสพัสดุ"],
      "bm_number": ["Customer TN", "Order SN", "Mã đơn hàng", "BM Number", "รหัสลูกค้า"],
      "shipping_fee": ["Shipping fee", "Shipping Fee", "Phí vận chuyển", "Cước phí", "ค่าขนส่ง", "ค่าจัดส่ง"],
      "cod_fee": ["COD fee", "COD Fee", "COD Amount", "Tiền thu hộ", "ค่า COD", "เงินเก็บเงินปลายทาง"],
      "weight": ["Chargeable weight", "Chargeable Weight", "Weight", "Trọng lượng", "น้ำหนัก", "น้ำหนักที่คิด"],
      "overweight_fee": ["Overweight fee", "Overweight Fee", "Phí vượt cân", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Remote Area", "Remote Area Fee", "Phụ phí vùng xa", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Insurance fee", "Insurance Fee", "Phí bảo hiểm", "ค่าประกัน"],
      "return_fee": ["Return fee", "Return Fee", "Phí hoàn", "ค่าคืน", "ค่าส่งคืน"],
      "other_fees": ["Administrative Fee", "Other Fees", "Phí khác", "ค่าอื่นๆ", "ค่าบริการ"],
      "status": ["Remark", "Status", "Trạng thái", "สถานะ", "หมายเหตุ"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "boxmeHints": {
      "tracking": ["Tracking number", "Mã vận đơn", "เลขพัสดุ", "Courier tracking code"],
      "shipping_fee": ["Shipping fee", "Phí vận chuyển", "ค่าขนส่ง", "Shipping fee (System)"],
      "cod_fee": ["Cod fee", "COD Amount", "Money colect", "Money collect", "Tiền thu hộ", "ค่า COD"],
      "weight": ["Weight", "Trọng lượng", "น้ำหนัก", "Chargeable FF Weight", "Fulfill CW"],
      "overweight_fee": ["Overweight fee", "Phí vượt cân", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Remote fee", "Remote Area", "Phụ phí vùng xa", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Insurance fee", "Phí bảo hiểm", "ค่าประกัน", "Extra service fee"],
      "return_fee": ["Return fee", "Phí hoàn", "ค่าคืน"],
      "other_fees": ["Other fee (Chang courier fee)", "Other fee", "Phí khác", "ค่าอื่นๆ"]
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "KERRY": {
    "name": "Kerry Express",
    "carrierSheetHint": ["invoice_details"],
    "boxmeSheetHint": ["Order"],
    "headerRowHint": 12,
    "carrierMapping": {
      "tracking": "Consignment No",
      "bm_number": "Ref No",
      "shipping_fee": "Freight Charge",
      "cod_fee": "COD Amount",
      "weight": "Chargeable Weight",
      "overweight_fee": "Overweight Charge",
      "remote_fee": "Remote Area Charge",
      "insurance_fee": "Insurance Charge",
      "return_fee": "Return Charge",
      "other_fees": "Other Charges",
      "status": "Status"
    },
    "carrierHints": {
      "tracking": ["Consignment No", "Consignment Number", "Tracking Number", "หมายเลขพัสดุ", "เลขพัสดุ", "Mã vận đơn"],
      "bm_number": ["Ref No", "Reference No", "Customer Ref", "หมายเลขอ้างอิง", "Mã tham chiếu"],
      "shipping_fee": ["Freight Charge", "Shipping Fee", "Delivery Fee", "ค่าขนส่ง", "ค่าจัดส่ง", "Phí vận chuyển"],
      "cod_fee": ["COD Amount", "COD Fee", "COD", "ค่า COD", "เงินเก็บเงินปลายทาง", "Tiền thu hộ"],
      "weight": ["Chargeable Weight", "Weight", "น้ำหนักที่คิด", "น้ำหนัก", "Trọng lượng"],
      "overweight_fee": ["Overweight Charge", "Overweight Fee", "ค่าน้ำหนักเกิน", "Phí vượt cân"],
      "remote_fee": ["Remote Area Charge", "Remote Area Fee", "ค่าพื้นที่ห่างไกล", "Phụ phí vùng xa"],
      "insurance_fee": ["Insurance Charge", "Insurance Fee", "ค่าประกัน", "ค่าประกันภัย", "Phí bảo hiểm"],
      "return_fee": ["Return Charge", "Return Fee", "ค่าคืนพัสดุ", "ค่าส่งคืน", "Phí hoàn"],
      "other_fees": ["Other Charges", "Other Fees", "ค่าอื่นๆ", "ค่าบริการอื่น", "Phí khác"],
      "status": ["Status", "สถานะ", "สถานะการจัดส่ง", "Trạng thái"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "FLASH": {
    "name": "Flash Express",
    "carrierSheetHint": ["Shipping"],
    "boxmeSheetHint": ["Order"],
    "headerRowHint": 2,
    "carrierMapping": {
      "tracking": "PNO",
      "bm_number": "Out Trade No",
      "shipping_fee": "Shipping Fee",
      "cod_fee": "COD Amount",
      "weight": "Weight (kg)",
      "overweight_fee": "Overweight Fee",
      "remote_fee": "Remote Area Fee",
      "insurance_fee": "Insurance Fee",
      "return_fee": "Return Fee",
      "other_fees": "Other Fees",
      "status": "Parcel Status"
    },
    "carrierHints": {
      "tracking": ["PNO", "Tracking Number", "หมายเลขพัสดุ", "เลขพัสดุ", "Mã vận đơn"],
      "bm_number": ["Out Trade No", "Reference No", "หมายเลขอ้างอิง", "Mã đơn hàng"],
      "shipping_fee": ["Shipping Fee", "Delivery Fee", "ค่าขนส่ง", "ค่าจัดส่ง", "Phí vận chuyển"],
      "cod_fee": ["COD Amount", "COD Fee", "ค่า COD", "เงินเก็บเงินปลายทาง", "Tiền thu hộ"],
      "weight": ["Weight", "Chargeable Weight", "น้ำหนัก", "น้ำหนักที่คิด", "Trọng lượng"],
      "overweight_fee": ["Overweight Fee", "ค่าน้ำหนักเกิน", "Phí vượt cân"],
      "remote_fee": ["Remote Area Fee", "Remote Area", "ค่าพื้นที่ห่างไกล", "Phụ phí vùng xa"],
      "insurance_fee": ["Insurance Fee", "ค่าประกันภัย", "ค่าประกัน", "Phí bảo hiểm"],
      "return_fee": ["Return Fee", "ค่าคืนพัสดุ", "ค่าส่งคืน", "Phí hoàn"],
      "other_fees": ["Other Fees", "ค่าอื่นๆ", "ค่าบริการอื่น", "Phí khác"],
      "status": ["Parcel Status", "Status", "สถานะ", "สถานะพัสดุ", "Trạng thái"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "JT_TH": {
    "name": "J&T Express TH",
    "carrierMapping": {
      "tracking": "Tracking No",
      "bm_number": "Customer Order No",
      "shipping_fee": "Delivery Fee",
      "cod_fee": "COD Amount",
      "weight": "Chargeable Weight (kg)",
      "overweight_fee": "Overweight Fee",
      "remote_fee": "Remote Area Surcharge",
      "insurance_fee": "Insurance Fee",
      "return_fee": "Return Fee",
      "other_fees": "Other Charges",
      "status": "Status"
    },
    "carrierHints": {
      "tracking": ["Tracking No", "Tracking Number", "เลขพัสดุ", "หมายเลขพัสดุ", "Mã vận đơn"],
      "bm_number": ["Customer Order No", "หมายเลขอ้างอิงลูกค้า", "Ref No", "Mã đơn hàng"],
      "shipping_fee": ["Delivery Fee", "Shipping Fee", "ค่าจัดส่ง", "ค่าขนส่ง", "Phí vận chuyển"],
      "cod_fee": ["COD Amount", "COD Fee", "ค่า COD", "เงินเก็บเงินปลายทาง", "Tiền thu hộ"],
      "weight": ["Chargeable Weight", "Weight", "น้ำหนักที่คิด", "น้ำหนัก", "Trọng lượng"],
      "overweight_fee": ["Overweight Fee", "ค่าน้ำหนักเกิน", "Phí vượt cân"],
      "remote_fee": ["Remote Area Surcharge", "Remote Area", "ค่าพื้นที่ห่างไกล", "Phụ phí vùng xa"],
      "insurance_fee": ["Insurance Fee", "ค่าประกัน", "ค่าประกันภัย", "Phí bảo hiểm"],
      "return_fee": ["Return Fee", "ค่าคืนพัสดุ", "ค่าส่งคืน", "Phí hoàn"],
      "other_fees": ["Other Charges", "Other Fees", "ค่าอื่นๆ", "Phí khác"],
      "status": ["Status", "สถานะ", "สถานะการจัดส่ง", "Trạng thái"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "NINJA_TH": {
    "name": "Ninja Van TH",
    "carrierMapping": {
      "tracking": "Tracking ID",
      "bm_number": "Shipper Order ID",
      "shipping_fee": "Delivery Fee",
      "cod_fee": "COD Amount",
      "weight": "Weight (kg)",
      "overweight_fee": "Overweight Fee",
      "remote_fee": "Remote Area Surcharge",
      "insurance_fee": "Insurance Fee",
      "return_fee": "Return Fee",
      "other_fees": "Other Fees",
      "status": "Granular Status"
    },
    "carrierHints": {
      "tracking": ["Tracking ID", "Tracking Number", "เลขพัสดุ", "หมายเลขพัสดุ", "Mã vận đơn"],
      "bm_number": ["Shipper Order ID", "Reference", "หมายเลขอ้างอิง", "Mã đơn hàng"],
      "shipping_fee": ["Delivery Fee", "Shipping Fee", "ค่าจัดส่ง", "ค่าขนส่ง", "Phí vận chuyển"],
      "cod_fee": ["COD Amount", "COD Fee", "ค่า COD", "เงินเก็บเงินปลายทาง", "Tiền thu hộ"],
      "weight": ["Weight", "Chargeable Weight", "น้ำหนัก", "น้ำหนักที่คิด", "Trọng lượng"],
      "overweight_fee": ["Overweight Fee", "ค่าน้ำหนักเกิน", "Phí vượt cân"],
      "remote_fee": ["Remote Area Surcharge", "Remote Area", "ค่าพื้นที่ห่างไกล", "Phụ phí vùng xa"],
      "insurance_fee": ["Insurance Fee", "ค่าประกัน", "ค่าประกันภัย", "Phí bảo hiểm"],
      "return_fee": ["Return Fee", "ค่าคืนพัสดุ", "ค่าส่งคืน", "Phí hoàn"],
      "other_fees": ["Other Fees", "ค่าอื่นๆ", "Phí khác"],
      "status": ["Granular Status", "Status", "สถานะ", "Trạng thái"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "SPX_TH": {
    "name": "Shopee Express TH",
    "carrierMapping": {
      "tracking": "Tracking number",
      "bm_number": "Customer TN",
      "shipping_fee": "Shipping fee",
      "cod_fee": "COD fee",
      "weight": "Chargeable weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote Area",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Administrative Fee",
      "status": "Remark"
    },
    "carrierHints": {
      "tracking": ["Tracking number", "Tracking Number", "เลขพัสดุ", "หมายเลขพัสดุ", "Mã vận đơn"],
      "bm_number": ["Customer TN", "Order SN", "BM Number", "รหัสลูกค้า", "Mã đơn hàng"],
      "shipping_fee": ["Shipping fee", "Shipping Fee", "ค่าขนส่ง", "ค่าจัดส่ง", "Phí vận chuyển", "Cước phí"],
      "cod_fee": ["COD fee", "COD Fee", "COD Amount", "ค่า COD", "เงินเก็บเงินปลายทาง", "Tiền thu hộ"],
      "weight": ["Chargeable weight", "Chargeable Weight", "Weight", "น้ำหนัก", "น้ำหนักที่คิด", "Trọng lượng"],
      "overweight_fee": ["Overweight fee", "Overweight Fee", "ค่าน้ำหนักเกิน", "Phí vượt cân"],
      "remote_fee": ["Remote Area", "Remote Area Fee", "ค่าพื้นที่ห่างไกล", "Phụ phí vùng xa"],
      "insurance_fee": ["Insurance fee", "Insurance Fee", "ค่าประกัน", "ค่าประกันภัย", "Phí bảo hiểm"],
      "return_fee": ["Return fee", "Return Fee", "ค่าคืน", "ค่าส่งคืน", "Phí hoàn"],
      "other_fees": ["Administrative Fee", "Other Fees", "ค่าบริการ", "ค่าอื่นๆ", "Phí khác"],
      "status": ["Remark", "Status", "สถานะ", "หมายเหตุ", "Trạng thái"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "boxmeHints": {
      "tracking": ["Tracking number", "Mã vận đơn", "เลขพัสดุ", "Courier tracking code"],
      "shipping_fee": ["Shipping fee", "Phí vận chuyển", "ค่าขนส่ง", "Shipping fee (System)"],
      "cod_fee": ["Cod fee", "COD Amount", "Money colect", "Money collect", "Tiền thu hộ", "ค่า COD"],
      "weight": ["Weight", "Trọng lượng", "น้ำหนัก", "Chargeable FF Weight", "Fulfill CW"],
      "overweight_fee": ["Overweight fee", "Phí vượt cân", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Remote fee", "Remote Area", "Phụ phí vùng xa", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Insurance fee", "Phí bảo hiểm", "ค่าประกัน", "Extra service fee"],
      "return_fee": ["Return fee", "Phí hoàn", "ค่าคืน"],
      "other_fees": ["Other fee (Chang courier fee)", "Other fee", "Phí khác", "ค่าอื่นๆ"]
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "JT_PH": {
    "name": "J&T Express PH",
    "carrierMapping": {
      "tracking": "Waybill No",
      "bm_number": "Customer Order No",
      "shipping_fee": "Freight Fee",
      "cod_fee": "COD Amount",
      "weight": "Chargeable Weight (kg)",
      "overweight_fee": "Overweight Fee",
      "remote_fee": "Remote Area Surcharge",
      "insurance_fee": "Insurance Fee",
      "return_fee": "Return Fee",
      "other_fees": "Other Charges",
      "status": "Status"
    },
    "carrierHints": {
      "tracking": ["Waybill No", "Tracking Number", "Tracking No", "เลขพัสดุ", "Mã vận đơn"],
      "bm_number": ["Customer Order No", "Reference No", "รหัสลูกค้า", "Mã đơn hàng"],
      "shipping_fee": ["Freight Fee", "Shipping Fee", "Delivery Fee", "ค่าจัดส่ง", "Phí vận chuyển"],
      "cod_fee": ["COD Amount", "COD Fee", "ค่า COD", "Tiền thu hộ"],
      "weight": ["Chargeable Weight", "Weight", "น้ำหนัก", "Trọng lượng"],
      "overweight_fee": ["Overweight Fee", "ค่าน้ำหนักเกิน", "Phí vượt cân"],
      "remote_fee": ["Remote Area Surcharge", "Remote Area", "ค่าพื้นที่ห่างไกล", "Phụ phí vùng xa"],
      "insurance_fee": ["Insurance Fee", "ค่าประกัน", "Phí bảo hiểm"],
      "return_fee": ["Return Fee", "ค่าคืน", "Phí hoàn"],
      "other_fees": ["Other Charges", "Other Fees", "ค่าอื่นๆ", "Phí khác"],
      "status": ["Status", "สถานะ", "Trạng thái"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "NINJA_PH": {
    "name": "Ninja Van PH",
    "carrierMapping": {
      "tracking": "Tracking ID",
      "bm_number": "Shipper Order ID",
      "shipping_fee": "Delivery Fee",
      "cod_fee": "COD Amount",
      "weight": "Weight (kg)",
      "overweight_fee": "Overweight Fee",
      "remote_fee": "Remote Area Surcharge",
      "insurance_fee": "Insurance Fee",
      "return_fee": "Return Fee",
      "other_fees": "Other Fees",
      "status": "Granular Status"
    },
    "carrierHints": {
      "tracking": ["Tracking ID", "Tracking Number", "เลขพัสดุ", "Mã vận đơn"],
      "bm_number": ["Shipper Order ID", "Reference", "Mã đơn hàng"],
      "shipping_fee": ["Delivery Fee", "Shipping Fee", "ค่าจัดส่ง", "Phí vận chuyển"],
      "cod_fee": ["COD Amount", "COD Fee", "ค่า COD", "Tiền thu hộ"],
      "weight": ["Weight", "Chargeable Weight", "น้ำหนัก", "Trọng lượng"],
      "overweight_fee": ["Overweight Fee", "ค่าน้ำหนักเกิน", "Phí vượt cân"],
      "remote_fee": ["Remote Area Surcharge", "Remote Area", "ค่าพื้นที่ห่างไกล", "Phụ phí vùng xa"],
      "insurance_fee": ["Insurance Fee", "ค่าประกัน", "Phí bảo hiểm"],
      "return_fee": ["Return Fee", "ค่าคืน", "Phí hoàn"],
      "other_fees": ["Other Fees", "ค่าอื่นๆ", "Phí khác"],
      "status": ["Granular Status", "Status", "สถานะ", "Trạng thái"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "FLASH_PH": {
    "name": "Flash Express PH",
    "carrierMapping": {
      "tracking": "PNO",
      "bm_number": "Out Trade No",
      "shipping_fee": "Shipping Fee",
      "cod_fee": "COD Amount",
      "weight": "Weight (kg)",
      "overweight_fee": "Overweight Fee",
      "remote_fee": "Remote Area Fee",
      "insurance_fee": "Insurance Fee",
      "return_fee": "Return Fee",
      "other_fees": "Other Fees",
      "status": "Parcel Status"
    },
    "carrierHints": {
      "tracking": ["PNO", "Tracking Number", "เลขพัสดุ", "Mã vận đơn"],
      "bm_number": ["Out Trade No", "Reference No", "Mã đơn hàng"],
      "shipping_fee": ["Shipping Fee", "Delivery Fee", "ค่าจัดส่ง", "Phí vận chuyển"],
      "cod_fee": ["COD Amount", "COD Fee", "ค่า COD", "Tiền thu hộ"],
      "weight": ["Weight", "Chargeable Weight", "น้ำหนัก", "Trọng lượng"],
      "overweight_fee": ["Overweight Fee", "ค่าน้ำหนักเกิน", "Phí vượt cân"],
      "remote_fee": ["Remote Area Fee", "Remote Area", "ค่าพื้นที่ห่างไกล", "Phụ phí vùng xa"],
      "insurance_fee": ["Insurance Fee", "ค่าประกัน", "Phí bảo hiểm"],
      "return_fee": ["Return Fee", "ค่าคืน", "Phí hoàn"],
      "other_fees": ["Other Fees", "ค่าอื่นๆ", "Phí khác"],
      "status": ["Parcel Status", "Status", "สถานะ", "Trạng thái"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "SPX_PH": {
    "name": "Shopee Express PH",
    "carrierMapping": {
      "tracking": "Tracking number",
      "bm_number": "Customer TN",
      "shipping_fee": "Shipping fee",
      "cod_fee": "COD fee",
      "weight": "Chargeable weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote Area",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Administrative Fee",
      "status": "Remark"
    },
    "carrierHints": {
      "tracking": ["Tracking number", "Tracking Number", "เลขพัสดุ", "Mã vận đơn"],
      "bm_number": ["Customer TN", "Order SN", "BM Number", "Mã đơn hàng"],
      "shipping_fee": ["Shipping fee", "Shipping Fee", "ค่าจัดส่ง", "Phí vận chuyển"],
      "cod_fee": ["COD fee", "COD Fee", "COD Amount", "ค่า COD", "Tiền thu hộ"],
      "weight": ["Chargeable weight", "Chargeable Weight", "Weight", "น้ำหนัก", "Trọng lượng"],
      "overweight_fee": ["Overweight fee", "Overweight Fee", "ค่าน้ำหนักเกิน", "Phí vượt cân"],
      "remote_fee": ["Remote Area", "Remote Area Fee", "ค่าพื้นที่ห่างไกล", "Phụ phí vùng xa"],
      "insurance_fee": ["Insurance fee", "Insurance Fee", "ค่าประกัน", "Phí bảo hiểm"],
      "return_fee": ["Return fee", "Return Fee", "ค่าคืน", "Phí hoàn"],
      "other_fees": ["Administrative Fee", "Other Fees", "ค่าอื่นๆ", "Phí khác"],
      "status": ["Remark", "Status", "สถานะ", "Trạng thái"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "GRAB_PH": {
    "name": "Grab Express PH",
    "carrierMapping": {
      "tracking": "Tracking Number",
      "bm_number": "Merchant Order ID",
      "shipping_fee": "Delivery Fee",
      "cod_fee": "COD Amount",
      "weight": "Weight (kg)",
      "overweight_fee": "Overweight Fee",
      "remote_fee": "Remote Area Surcharge",
      "insurance_fee": "Insurance Fee",
      "return_fee": "Return Fee",
      "other_fees": "Other Charges",
      "status": "Delivery Status"
    },
    "carrierHints": {
      "tracking": ["Tracking Number", "Tracking No", "เลขพัสดุ", "Mã vận đơn"],
      "bm_number": ["Merchant Order ID", "Order ID", "Mã đơn hàng"],
      "shipping_fee": ["Delivery Fee", "Shipping Fee", "ค่าจัดส่ง", "Phí vận chuyển"],
      "cod_fee": ["COD Amount", "COD Fee", "ค่า COD", "Tiền thu hộ"],
      "weight": ["Weight", "Chargeable Weight", "น้ำหนัก", "Trọng lượng"],
      "overweight_fee": ["Overweight Fee", "ค่าน้ำหนักเกิน", "Phí vượt cân"],
      "remote_fee": ["Remote Area Surcharge", "Remote Area", "ค่าพื้นที่ห่างไกล", "Phụ phí vùng xa"],
      "insurance_fee": ["Insurance Fee", "ค่าประกัน", "Phí bảo hiểm"],
      "return_fee": ["Return Fee", "ค่าคืน", "Phí hoàn"],
      "other_fees": ["Other Charges", "Other Fees", "ค่าอื่นๆ", "Phí khác"],
      "status": ["Delivery Status", "Status", "สถานะ", "Trạng thái"]
    },
    "boxmeMapping": {
      "tracking": "Tracking number",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "DHL_TH": {
    "name": "DHL Express TH",
    "carrierSheetHint": ["Shipping"],
    "boxmeSheetHint": ["Order"],
    "headerRowHint": 13,
    "carrierMapping": {
      "tracking": "Consignment Note No.",
      "bm_number": "Customer Reference 2",
      "shipping_fee": "Net Amount (Excl Taxes)",
      "cod_fee": "CoD Amount",
      "weight": "Chargable Weight",
      "overweight_fee": "",
      "remote_fee": "Freight Remote Area",
      "insurance_fee": "",
      "return_fee": "",
      "other_fees": "Fuel Surcharge",
      "status": ""
    },
    "carrierHints": {
      "tracking": ["Consignment Note No.", "Consignment Note", "Parcel ID", "Tracking Number", "เลขพัสดุ", "หมายเลขพัสดุ"],
      "bm_number": ["Customer Reference 2", "Customer Tracking No.", "Customer Reference", "Pick Up Account Name", "รหัสลูกค้า"],
      "shipping_fee": ["Net Amount (Excl Taxes)", "Total Amount (Incl Taxes)", "Total Amount", "ค่าขนส่ง", "ค่าจัดส่ง"],
      "cod_fee": ["CoD Amount", "COD Amount", "COD", "ค่า COD"],
      "weight": ["Chargable Weight", "Actual Weight", "Announce Weight", "น้ำหนัก"],
      "overweight_fee": ["Overweight Fee", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Freight Remote Area", "Remote Area", "Special Zone", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Insurance Fee", "SVP declared value", "ค่าประกัน"],
      "return_fee": ["Return Fee", "ค่าคืน"],
      "other_fees": ["Fuel Surcharge", "Peak Surcharge", "Discount Amount", "ค่าอื่นๆ"],
      "status": ["Status", "สถานะ"]
    },
    "boxmeMapping": {
      "tracking": "Courier tracking code",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Chargeable FF Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "boxmeHints": {
      "tracking": ["Courier tracking code", "Tracking number", "เลขพัสดุ"],
      "shipping_fee": ["Shipping fee", "ค่าขนส่ง"],
      "cod_fee": ["Cod fee", "COD Amount", "Money colect", "Money collect", "ค่า COD"],
      "weight": ["Chargeable FF Weight", "Weight", "Fulfill CW", "น้ำหนัก"],
      "overweight_fee": ["Overweight fee", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Remote fee", "Remote Area", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Insurance fee", "Extra service fee", "ค่าประกัน"],
      "return_fee": ["Return fee", "ค่าคืน"],
      "other_fees": ["Other fee (Chang courier fee)", "Other fee", "ค่าอื่นๆ"]
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "INTER_TH": {
    "name": "Inter Express (SJ Trans)",
    "carrierSheetHint": ["SJ Trans"],
    "boxmeSheetHint": ["Order"],
    "headerRowHint": 4,
    "carrierMapping": {
      "tracking": "BARCODE",
      "bm_number": "Order ID",
      "shipping_fee": "PRICE",
      "cod_fee": "",
      "weight": "WEIGHT",
      "overweight_fee": "",
      "remote_fee": "",
      "insurance_fee": "INSURANCE",
      "return_fee": "",
      "other_fees": "",
      "status": ""
    },
    "carrierHints": {
      "tracking": ["BARCODE", "Tracking Number", "เลขพัสดุ", "หมายเลขพัสดุ", "เลขที่อ้างอิงอื่น ๆ"],
      "bm_number": ["Order ID", "Customer Ref", "รหัสลูกค้า", "เลขที่อ้างอิง"],
      "shipping_fee": ["PRICE", "Total Price", "ค่าขนส่ง", "ค่าจัดส่ง"],
      "cod_fee": ["COD Amount", "COD", "ค่า COD"],
      "weight": ["WEIGHT", "น้ำหนัก"],
      "overweight_fee": ["Overweight Fee", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Remote Area", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["INSURANCE", "Insurance Fee", "ค่าประกัน"],
      "return_fee": ["Return Fee", "ค่าคืน"],
      "other_fees": ["Other Fees", "ค่าอื่นๆ"],
      "status": ["STATUS", "Status", "สถานะ"]
    },
    "boxmeMapping": {
      "tracking": "Courier tracking code",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Chargeable FF Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "boxmeHints": {
      "tracking": ["Courier tracking code", "Tracking number", "เลขพัสดุ"],
      "shipping_fee": ["Shipping fee", "ค่าขนส่ง"],
      "cod_fee": ["Cod fee", "COD Amount", "Money colect", "Money collect", "ค่า COD"],
      "weight": ["Chargeable FF Weight", "Weight", "Fulfill CW", "น้ำหนัก"],
      "overweight_fee": ["Overweight fee", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Remote fee", "Remote Area", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Insurance fee", "Extra service fee", "ค่าประกัน"],
      "return_fee": ["Return fee", "ค่าคืน"],
      "other_fees": ["Other fee (Chang courier fee)", "Other fee", "ค่าอื่นๆ"]
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "NIM_TH": {
    "name": "NIM Express",
    "carrierSheetHint": ["รายงาน"],
    "boxmeSheetHint": ["Order"],
    "headerRowHint": 3,
    "carrierMapping": {
      "tracking": "เลขที่อ้างอิงอื่น ๆ",
      "bm_number": "รหัสลูกค้า",
      "shipping_fee": "ค่าขนส่ง",
      "cod_fee": "",
      "weight": "น้ำหนัก",
      "overweight_fee": "",
      "remote_fee": "",
      "insurance_fee": "",
      "return_fee": "",
      "other_fees": "",
      "status": ""
    },
    "carrierHints": {
      "tracking": ["เลขที่อ้างอิงอื่น ๆ", "เลขที่บิล", "BARCODE", "Tracking Number", "เลขพัสดุ", "หมายเลขพัสดุ"],
      "bm_number": ["รหัสลูกค้า", "Customer Ref", "Order ID", "เลขที่อ้างอิงลูกค้า"],
      "shipping_fee": ["ค่าขนส่ง", "Shipping Fee", "ค่าจัดส่ง"],
      "cod_fee": ["COD Amount", "COD", "ค่า COD"],
      "weight": ["น้ำหนัก", "Weight"],
      "overweight_fee": ["ค่าน้ำหนักเกิน", "Overweight Fee"],
      "remote_fee": ["ค่าข้ามเกาะ", "Remote Area", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["ค่าประกัน", "Insurance Fee"],
      "return_fee": ["ค่าคืน", "Return Fee"],
      "other_fees": ["ค่าอื่นๆ", "Other Fees"],
      "status": ["สถานะ", "Status"]
    },
    "boxmeMapping": {
      "tracking": "Courier tracking code",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Chargeable FF Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "boxmeHints": {
      "tracking": ["Courier tracking code", "Tracking number", "เลขพัสดุ"],
      "shipping_fee": ["Shipping fee", "ค่าขนส่ง"],
      "cod_fee": ["Cod fee", "COD Amount", "Money colect", "Money collect", "ค่า COD"],
      "weight": ["Chargeable FF Weight", "Weight", "Fulfill CW", "น้ำหนัก"],
      "overweight_fee": ["Overweight fee", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Remote fee", "Remote Area", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Insurance fee", "Extra service fee", "ค่าประกัน"],
      "return_fee": ["Return fee", "ค่าคืน"],
      "other_fees": ["Other fee (Chang courier fee)", "Other fee", "ค่าอื่นๆ"]
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  },
  "TLP_TH": {
    "name": "Thailand Post (TLP)",
    "carrierSheetHint": ["THailand Post", "Thailand Post"],
    "boxmeSheetHint": ["Order"],
    "headerRowHint": 1,
    "carrierMapping": {
      "tracking": "BARCODE",
      "bm_number": "COMP_ORDER_ID",
      "shipping_fee": "EMS_PRICE",
      "cod_fee": "PRODUCT_PRICE",
      "weight": "PRODUCT_WEIGHT",
      "overweight_fee": "",
      "remote_fee": "",
      "insurance_fee": "INSURANCE_PRICE",
      "return_fee": "",
      "other_fees": "SERVICE_PRICE",
      "status": "STATUS_DESC"
    },
    "carrierHints": {
      "tracking": ["BARCODE", "INV_NO", "Tracking Number", "เลขพัสดุ", "หมายเลขพัสดุ"],
      "bm_number": ["COMP_ORDER_ID", "ORDER_ID", "Customer Ref", "รหัสลูกค้า"],
      "shipping_fee": ["EMS_PRICE", "Shipping Fee", "ค่าขนส่ง", "ค่า EMS"],
      "cod_fee": ["PRODUCT_PRICE", "COD Amount", "ค่า COD"],
      "weight": ["PRODUCT_WEIGHT", "Weight", "น้ำหนัก"],
      "overweight_fee": ["Overweight Fee", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["พื้นที่พิเศษ", "Remote Area", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["INSURANCE_PRICE", "Insurance Fee", "ค่าประกัน"],
      "return_fee": ["Return Fee", "ค่าคืน"],
      "other_fees": ["SERVICE_PRICE", "Other Fees", "ค่าอื่นๆ", "ค่าบริการ"],
      "status": ["STATUS_DESC", "Status", "สถานะ"]
    },
    "boxmeMapping": {
      "tracking": "Courier tracking code",
      "shipping_fee": "Shipping fee",
      "cod_fee": "Cod fee",
      "weight": "Chargeable FF Weight",
      "overweight_fee": "Overweight fee",
      "remote_fee": "Remote fee",
      "insurance_fee": "Insurance fee",
      "return_fee": "Return fee",
      "other_fees": "Other fee (Chang courier fee)"
    },
    "boxmeHints": {
      "tracking": ["Courier tracking code", "Tracking number", "เลขพัสดุ"],
      "shipping_fee": ["Shipping fee", "ค่าขนส่ง"],
      "cod_fee": ["Cod fee", "COD Amount", "Money colect", "Money collect", "ค่า COD"],
      "weight": ["Chargeable FF Weight", "Weight", "Fulfill CW", "น้ำหนัก"],
      "overweight_fee": ["Overweight fee", "ค่าน้ำหนักเกิน"],
      "remote_fee": ["Remote fee", "Remote Area", "ค่าพื้นที่ห่างไกล"],
      "insurance_fee": ["Insurance fee", "Extra service fee", "ค่าประกัน"],
      "return_fee": ["Return fee", "ค่าคืน"],
      "other_fees": ["Other fee (Chang courier fee)", "Other fee", "ค่าอื่นๆ"]
    },
    "updatedAt": "2026-03-10T00:00:00.000Z"
  }
}
